image:
  repository: selcucommonacr.azurecr.io/selfcaremsproduct
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://uat.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - uat01.pnpg.internal.uat.selfcare.pagopa.it
      secretName: uat01-pnpg-internal-uat-selfcare-pagopa-it
  hosts:
    - host: "uat01.pnpg.internal.uat.selfcare.pagopa.it"
      paths:
        - path: /ms-product/v1/(.*)
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: "0.1"
    memory: "128Mi"
  limits:
    cpu: "0.5"
    memory: "256Mi"
    
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_PRODUCT_LOG_LEVEL: "INFO"
  LOGO_STORAGE_URL: ""
  DEPICT_IMAGE_URL: ""
