image:
  repository: selcdcommonacr.azurecr.io/selfcaremsproduct

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - dev01.pnpg.internal.dev.selfcare.pagopa.it
      secretName: dev01-pnpg-internal-dev-selfcare-pagopa-it
  hosts:
    - host: "dev01.pnpg.internal.dev.selfcare.pagopa.it"
      paths:
        - path: /ms-product/v1/(.*)
          pathType: ImplementationSpecific


resources:
  requests:
    cpu: "0.1"
    memory: "128Mi"
  limits:
    cpu: "0.5"
    memory: "256Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_PRODUCT_LOG_LEVEL: "DEBUG"
  LOGO_STORAGE_URL: ""
  DEPICT_IMAGE_URL: ""
