image:
  repository: selcpcommonacr.azurecr.io/selfcaremsproduct
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 0.0.1-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://imprese.notifichedigitali.it,https://pnpg.selfcare.pagopa.it"
  tls:
    - hosts:
        - prod01.pnpg.internal.selfcare.pagopa.it
      secretName: prod01-pnpg-internal-selfcare-pagopa-it
  hosts:
    - host: "prod01.pnpg.internal.selfcare.pagopa.it"
      paths:
        - path: /ms-product/v1/(.*)
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  MS_PRODUCT_LOG_LEVEL: "INFO"
  LOGO_STORAGE_URL: ""
  DEPICT_IMAGE_URL: ""
