server:
  port: ${SELC_PRODUCT_PORT:8080}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable italian documentations
      - swaggerIT

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"


logging:
  level:
    it.pagopa.selfcare.product: ${LOG_LEVEL_SELC_PRODUCT:DEBUG}