apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "selfcare-ms-product.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  {{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.configEnvSpecific }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
