apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msproduct
  name: msproduct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msproduct
  template:
    metadata:
      labels:
        app: msproduct
    spec:
      containers:
        - name: msproduct
          image: selcuacr.azurecr.io/msproduct
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: application-insights
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
