# Default values for selfcare-ms-product.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: selc

replicaCount: 1

image:
  repository: selcdacr.azurecr.io/selfcaremsproduct
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "ms-product"

containers:
  portNumber: 8080

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: ""
  annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/rewrite-target: "/$1"
   nginx.ingress.kubernetes.io/ssl-redirect: "false"
   nginx.ingress.kubernetes.io/use-regex: "true"
   nginx.ingress.kubernetes.io/enable-cors: "true"
   nginx.ingress.kubernetes.io/cors-allow-headers: "*"
   nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it"
  hosts:
    - host: ""
      paths:
        - path: /ms-product/v1/(.*)
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: "0.1"
    memory: "256Mi"
  limits:
    cpu: "0.5"
    memory: "512Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  MONGODB_NAME: selcProduct
  APPLICATIONINSIGHTS_ROLE_NAME: "ms-product"